version: '3'

networks:
    webkey-privacy-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.1.1.0/24

services:
    # database service
    webkey-privacy-database:
        container_name: webkey-privacy-database
        image: mariadb:${MARIADB_VERSION:-latest}
        hostname: webkey-privacy-database
        restart: ${RESTART_POLICY:-unless-stopped}
        volumes:
            - ./storage/database/mariadb:/var/lib/mysql
            - ./storage/database/log:/var/log/mysql
        networks:
            webkey-privacy-network:
                ipv4_address: 172.1.1.2
        healthcheck:
            test: ['CMD', 'healthcheck.sh', '--connect --innodb_initialized']
            retries: 3
            timeout: 5s

    # redis service
    webkey-privacy-redis:
        container_name: webkey-privacy-redis
        image: redis:alpine
        hostname: webkey-privacy-redis
        restart: ${RESTART_POLICY:-unless-stopped}
        volumes:
            - ./storage/database/redis:/data
        networks:
            webkey-privacy-network:
                ipv4_address: 172.1.1.3
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            retries: 3
            timeout: 5s

    # phpmyadmin web app
    webkey-privacy-phpmyadmin:
        container_name: webkey-privacy-phpmyadmin
        image: phpmyadmin:latest
        hostname: webkey-privacy-phpmyadmin
        restart: ${RESTART_POLICY:-unless-stopped}
        depends_on:
            - webkey-privacy-database
        environment:
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
        networks:
            webkey-privacy-network:
                ipv4_address: 172.1.1.4

    # webkey privacy app
    webkey-privacy-app:
        container_name: webkey-privacy-app
        image: php:webkey-privacy-app
        build: ./docker/php
        hostname: webkey-privacy-app
        restart: ${RESTART_POLICY:-unless-stopped}
        working_dir: /var/www/html
        depends_on:
            - webkey-privacy-database
            - webkey-privacy-redis
        volumes:
            - .:/var/www/html
        networks:
            webkey-privacy-network:
                ipv4_address: 172.1.1.5

    # webkey privacy web
    webkey-privacy-web:
        container_name: webkey-privacy-web
        image: nginx:alpine
        hostname: webkey-privacy-web
        restart: ${RESTART_POLICY:-unless-stopped}
        depends_on:
            - webkey-privacy-app
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./:/var/www/html
        networks:
            webkey-privacy-network:
                ipv4_address: 172.1.1.10
