version: '3'

networks:
    webkey-network:
        driver: bridge

services:
    # webkey database
    webkey-database:
        container_name: webkey-database
        image: mariadb:latest
        hostname: webkey-database
        restart: ${RESTART_POLICY:-unless-stopped}
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-rootP@ssw0rd}
            - MARIADB_DATABASE=${MARIADB_DATABASE:-webkey}
            - MARIADB_USER=${MARIADB_USER:-webkey}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD:-webkeyP@ssw0rd}
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
        volumes:
            - ./var/database/data:/var/lib/mysql
            - ./var/database/log:/var/log/mysql
        networks:
            - webkey-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MARIADB_PASSWORD}"]
            retries: 3
            timeout: 5s

    # emd phpmyadmin
    webkey-phpmyadmin:
        container_name: webkey-phpmyadmin
        image: phpmyadmin:latest
        hostname: webkey-phpmyadmin
        restart: ${RESTART_POLICY:-unless-stopped}
        depends_on:
            - webkey-database
        environment:
            - PMA_HOST=${PMA_HOST:-webkey-database}
            - PMA_PORT=${PMA_PORT:-3306}
            - PMA_USER=${PMA_USER:-root}
            - PMA_PASSWORD=${PMA_PASSWORD:-rootP@ssw0rd}
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
        ports:
            - "${PMA_HTTP_PORT:-9090}:80"
        networks:
            - webkey-network

    # webkey app
    webkey-app:
        container_name: webkey-app
        image: php:alpine
        build: ./docker/php
        hostname: webkey-app
        restart: ${RESTART_POLICY:-unless-stopped}
        working_dir: /var/www
        command: php -S 0.0.0.0:${HTTP_PORT:-8080} -t public
        depends_on:
            - webkey-database
        environment:
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
        ports:
            - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
        volumes:
            - .:/var/www
        networks:
            - webkey-network
