version: '3'

networks:
    webkey-network:
        driver: bridge

services:
    # webkey database
    webkey-database:
        container_name: webkey-database
        image: mariadb:${MARIADB_VERSION:-latest}
        hostname: webkey-database
        restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-rootP@ssw0rd}
            - MARIADB_DATABASE=${MARIADB_DATABASE:-webkey}
            - MARIADB_USER=${MARIADB_USER:-webkey}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD:-webkeyP@ssw0rd}
            - TZ=${DOCKER_TIMEZONE:-Asia/Ho_Chi_Minh}
        volumes:
            - ${DOCKER_VOLUMES:-./var/data}/database:/var/lib/mysql
        networks:
            - webkey-network

    # webkey app
    webkey-app:
        container_name: webkey-app
        image: php:alpine
        hostname: webkey-app
        restart: ${DOCKER_RESTART_POLICY:-unless-stopped}
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        depends_on:
            - webkey-database
        environment:
            - TZ=${DOCKER_TIMEZONE:-Asia/Ho_Chi_Minh}
        ports:
            - "${DOCKER_HTTP_PORT:-8080}:8080"
        volumes:
            - .:/var/www
            - ./var/log:/var/www/logs
        networks:
            - webkey-network
